export const EVENTS: IEvent[] = [
  {
    id: "ab",
    name: "Tech Conference 2026",
    startDate: "2026-04-01T09:00:00Z",
    endDate: "2026-04-01T17:00:00Z",
    location: "San Francisco, CA",
    description: "Join us for a day of tech talks and networking.",
    thumbnail: "https://example.com/event1.jpg",
    liveStreamUrl: "https://example.com/event1-live",
    paymentStatus: "paid",
    isOffline: false,
    replayAvailable: true,
  },
  {
    id: "abc",
    name: "Music Festival 2026",
    startDate: "2026-03-20T12:00:00Z",
    endDate: "2026-03-20T23:00:00Z",
    location: "Austin, TX",
    description: "Experience live music from top artists around the world.",
    thumbnail: "https://example.com/event2.jpg",
    liveStreamUrl: "https://example.com/event2-live",
    paymentStatus: "unpaid",
    isOffline: true,
    replayAvailable: false,
  },
  {
    id: "abcd",
    name: "Art Expo 2026",
    startDate: "2026-11-05T10:00:00Z",
    endDate: "2026-11-05T18:00:00Z",
    location: "New York, NY",
    description: "Explore contemporary art from emerging artists.",
    thumbnail: "https://example.com/event3.jpg",
    liveStreamUrl: "https://example.com/event3-live",
    paymentStatus: "pending",
    isOffline: false,
    replayAvailable: true,
  },
  {
    id: "abcde",
    name: "Workshop 2026",
    startDate: "2026-12-10T09:00:00Z",
    endDate: "2026-12-10T16:00:00Z",
    location: "Los Angeles, CA",
    description: "Learn new skills from industry experts.",
    thumbnail: "https://example.com/event4.jpg",
    liveStreamUrl: "https://example.com/event4-live",
    paymentStatus: "paid",
    isOffline: false,
    replayAvailable: true,
  },
  {
    id: "abcdef",
    name: "Webinar 2026",
    startDate: "2026-12-20T14:00:00Z",
    endDate: "2026-12-20T15:30:00Z",
    location: "Online",
    description: "Join our expert panel for an interactive discussion.",
    thumbnail: "https://example.com/event5.jpg",
    liveStreamUrl: "https://example.com/event5-live",
    paymentStatus: "unpaid",
    isOffline: false,
    replayAvailable: false,
  },
];
